spring.datasource.url=jdbc:mysql://localhost:3306/projectb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.secret=ThisIsASecretKeyForCPT202ProjectBBookingSystemDoNotShare
jwt.expiration=86400000
